/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  azuremlSidebar: [
    {
      type: 'category',
      label: 'Fundamentals',
      items:[
          'azureml/fundamentals/azureml-basic',
          'azureml/fundamentals/azureml-resources-assets',
          'azureml/fundamentals/azureml-author',
          'azureml/fundamentals/azureml-api'
      ]
    },
    {
      type: 'category',
      label: 'Platform',
      items:[
          'azureml/platform/azureml-compute'
      ]
    },
    // {
    //   type: 'category',
    //   label: 'MLOps',
    //   items:[
    //     {
    //       type: 'autogenerated',
    //       dirName: 'azureml/mlops',
    //     }
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'Accerelation',
    //   items:[
    //     {
    //       type: 'autogenerated',
    //       dirName: 'azureml/acceleration',
    //     }
    //   ]
    // },
    {
      type: 'category',
      label: 'Responsible AI',
      collapsed: false,
      items:[
            'azureml/responsible-ai/rai-concept',
            {
              type: 'category',
              label: '責任のある AI の技術',
              link:{type: 'generated-index'},
              collapsed: true,
              items:[
                'azureml/responsible-ai/rai-tech-debugging',
                'azureml/responsible-ai/rai-tech-decision-making',
                'azureml/responsible-ai/rai-tech-security-privacy'
              ]
            },
        'azureml/responsible-ai/rai-reference',
      ]
    },
  ],

  tutorialSidebar:[
    {
      type: 'category',
      label: 'Docusaurus - Tutorials',
      items:[
        {
          type: 'autogenerated',
          dirName: 'docusaurus-tutorials',
        }
      ]
    },
  ]

};

module.exports = sidebars;
